services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osteotomy_flask
    ports:
      - "127.0.0.1:8000:8000"  # Bind Gunicorn inside the container to localhost on the host (port 8000)
    environment:
      FLASK_CONFIG: "production"
      FLASK_APP: "flask_app/app.py"
    volumes:
      - ./flask_app:/app/flask_app  # Optional: For development, hot-reload base app
    command: ./boot.sh
    restart: always