FROM python:3.8-slim-buster

RUN adduser --debug --disabled-password osteotomy

WORKDIR /home/osteotomy

COPY common.txt .
COPY docker.txt .
RUN python -m venv venv
RUN pip install --upgrade pip
RUN pip install -r docker.txt

# COPY flask_app flask_app
# COPY migrations migrations
# COPY osteotomy.py config.py boot.sh ./

COPY . .
RUN chmod +x boot.sh

ENV FLASK_APP osteotomy.py
# ENV FLASK_CONFIG=development

# remove before deploy
# ENV FLASK_DEBUG=1

RUN chown -R osteotomy:osteotomy ./
USER osteotomy

EXPOSE 8000
ENTRYPOINT ["./boot.sh"]